name: Update Code of Conduct
on:
  push:
    paths:
      - 'README.js'

jobs:
  update_code_of_conduct:
    runs-on: ubuntu-latest
    
    steps:
    - name: Copy file to new repo
      inputs:
        repo:
          description: 'github-actions-testing1'
          required: true
        path:
          description: 'README.md'
          required: true
        token: ${{ secrets.GITHUB_TOKEN }}
      run: node github-actions/copy-file-to-new-repo.js