name: Update Code of Conduct
on:
  push:
    paths:
      - 'README.md'

jobs:
  update_code_of_conduct:
    runs-on: ubuntu-latest
    
    steps:    
    # setup node 
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
        
    - name: Copy file to new repo
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
      run: node github-action/copy-file-to-new-repo.js