name: Update Code of Conduct
on:
  push:
    paths:
      - 'README.md'

jobs:
  update_code_of_conduct:
    runs-on: ubuntu-latest
    
    steps:
    - name: GitHub Action for install npm dependencies
      uses: bahmutov/npm-install@v1
      with:
        working-directory: ./github-action
    - name: Copy file to new repo
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
      run: node github-action/copy-file-to-new-repo.js