name: Schedule Daily 1100

# Run this action every day at 3am Pacific (11 am UTC)
on:
  push:
    paths:
      - 'README.js'

jobs:
  update_code_of_conduct:
    runs-on: ubuntu-latest
    
    steps:
    - name: Copy file to new repo
      inputs:
        repo:
          description: 'github-actions-testing1'
          required: true
        path:
          description: 'README.md'
          required: true
        token: ${{ secrets.GITHUB_TOKEN }}
      runs:
        using: 'node16'
        main: 'github-actions/copy-file-to-new-repo.js'