name: Update Code of Conduct

on:
  push:
    paths:
      - 'README.md'

jobs:
  update_code_of_conduct:
    runs-on: ubuntu-latest
    steps:
    - name: Copy file to new repo
      with:
        repo: 'github-actions-testing1'
        path: 'README.md'
        token: ${{ secrets.GITHUB_TOKEN }}
      run: node github-actions/copy-file-to-new-repo.js